### PR TITLE
Allow sourcing the zshrc and show all completions

### PR DESCRIPTION
**Pull request by jandamm**
I've found a way to make the capture script work with sourcing the `.zshrc`.
However there might be zsh plugins out there interfering with this method...

Feel free to close this pr if you don't feel comfortable with the changes.

### CODE REVIEW

**Comment by tamago324** [comment]
Thanks for the PR!
I'm not familiar with zsh, so I can't determine if this code is correct or not, but it's working as expected and I'd like to merge it!

**Comment by jandamm** [comment]
It's not specifically that the code is not correct but zsh has many options a user could apply in their zshrc which could break the script.
But in this case there's still the option to disable this feature.

**Comment by tamago324** [comment]
@jandamm 
Is there any way to run the program without leaving the following history?
Could you create a PR for me when you have time?

```zsh
source /tmp/zshX2QOvB
autoload add-zsh-hook
add-zsh-hook -D precmd '*'
add-zsh-hook -D preexec '*'
PROMPT=
echo thisisalonganduniquestringtomarktheendoftheinit >/dev/null
```

It's my project, and I'm sorry for the help.

**Comment by jandamm** [comment]
It's possible, I'll implement something later this week.

**Comment by tamago324** [comment]
@jandamm 
Thank you!
I'm not in a hurry, so please take your time.
I'm sorry for the inconvenience, but I appreciate your patience.

**Comment by jandamm** [comment]
Should be fixed in the new pr

**Pull request merged**
